const productos = [
    {
        id: 01,
        nombre: "Musculosa Basquet",
        precio: 2600,
        img: "./img/01musculosaBasquetJuego.jpg",
        cantidad: 1,
    },
    {
        id: 02,
        nombre: "Sudadera Basquet",
        precio: 2100,
        img: "./img/02sudaderaBasquetNegra.jpg",
        cantidad: 1,
    },
    {
        id: 03,
        nombre: "Conjunto Futbol",
        precio: 5700,
        img: "./img/03conjuntoFutbol.jpg",
        cantidad: 1,
    },
    {
        id: 04,
        nombre: "Pamtalon Largo",
        precio: 6800,
        img: "./img/04equipoLargoNegro.jpg",
        cantidad: 1,
    },
    {
        id: 05,
        nombre: "Equipo Voley",
        precio: 7900,
        img: "./img/05calzasNegras.jpg",
        cantidad: 1,
    },
    {
        id: 06,
        nombre: "conjunto Voley",
        precio: 6900,
        img: "./img/06mediasBlancas.jpg",
        cantidad: 1,
    },
    {
        id: 07,
        nombre: "Conjunto Tennis",
        precio: 8900,
        img: "./img/07mediasNegras.jpg",
        cantidad: 1,
    },
    {
        id: 08,
        nombre: "Remera Negra",
        precio: 4500,
        img: "./img/08mochilaNegra.jpg",
        cantidad: 1,
    },
    {
        id: 09,
        nombre: "Remera Juego M.C.",
        precio: 3500,
        img: "./img/09musculosaReversibleBn.jpg",
        cantidad: 1,
    },
    {
        id: 10,
        nombre: "Remera Gris",
        precio: 3200,
        img: "./img/10musculosaVoley.jpg",
        cantidad: 1,
    },
    ];